server:
  host: 0.0.0.0
  port: 3000
  options:
    connections:
      routes:
        cors:
          origin:
            - 'http://0.0.0.0:4200'
            - 'http://localhost:4200'
            - 'http://127.0.0.1:4200'
swagger:
  title: AutoConfig Back-End
  description: API for AutoConfig application
  version: 1.2.2
  tag: autoConfig
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/techWeb
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
