server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: AutoConfig Back-End
  description: API for AutoConfig application
  version: 1.0
  tag: autoConfig
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/techWeb
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
